### ISSUE TITLE
VOICEVOX Nemoの声を登録するには

### ISSUE THREAD

**Issue by stIprurIJu** [shigobu/SAPIForVOICEVOX#105]
VOICEVOX Nemoの声を使いたいのですが、やり方が解りません。

**Comment by shigobu** [comment]
返信おそくなりまして、すみません。
readmeをご覧ください。
https://github.com/shigobu/SAPIForVOICEVOX#voicevox%E6%B4%BE%E7%94%9F%E3%82%A2%E3%83%97%E3%83%AA%E3%81%AE%E3%82%AD%E3%83%A3%E3%83%A9%E3%82%AF%E3%82%BF%E3%83%BC%E7%99%BB%E9%8C%B2%E3%83%90%E3%83%BC%E3%82%B8%E3%83%A7%E3%83%B3-200%E4%BB%A5%E9%99%8D
