### ISSUE TITLE
SAPI登録行う際アプリ名が異なっていても、キャラとスタイルが同一の場合の重複登録が不能

### ISSUE THREAD

**Issue by Parfaitomcat** [shigobu/SAPIForVOICEVOX#108]
SAPI　登録を行う際に、キャラとスタイルのみで重複の確認を行っているようであり、
キャラ名とスタイル名が重複している音声を複数のエンジンで登録ができない

例：　Coeiroink 　つくよみちゃん　れいせい　と
　　　Coeiroink V2　つくよみちゃん　れいせい

**Comment by shigobu** [comment]
報告ありがとうございます。
確かに、そのような実装になっていました。
https://github.com/shigobu/SAPIForVOICEVOX/blob/125e2d43c70098d8cf33738a8d80aec5090786c2/SFVvCommon/SapiStyle.cs#L55
近い内に修正します。

**Comment by shigobu** [comment]
@Parfaitomcat 
バージョン2.1.8をリリースしました。
修正されているはずです。ご確認ください。

**Comment by Parfaitomcat** [comment]
かくにんしました。
ありがとうございました。
