### ISSUE TITLE
音声の先頭にノイズを伴う場合がある。

### ISSUE THREAD

**Issue by syunin-3** [shigobu/SAPIForVOICEVOX#19]
○環境
・SAPIForVOICEVOX 1.0.3
・VOICEVOX 0.5.1
・Windows10
　バージョン 21H1(OSビルド 19043.1165)

○事象
音声認識のプロパティで、コンピューターの既定の音声として「VOICEVOX ずんだもん」を選択した場合に、
音声の先頭にノイズを伴う場合があります。

https://user-images.githubusercontent.com/47511040/132969776-e62c89dc-85cf-408e-a3c5-a1ebd56e60c5.mp4

ノイズが伴う環境では、他のアプリケーションでも同様のノイズが発生していました。
※Excelの読み上げ機能で確認

既定の音声を「VOICEVOX 四国めたん」に切り替えたらノイズが発生しなくなり、
「VOICEVOX ずんだもん」に戻したところ、事象が再現しなくなりました。
環境依存かもしれないですが、念のため報告します。

**Comment by shigobu** [comment]
1.1.0をリリースしました。
おそらく、この問題が解消されていると思われるので、確認をしていただきたいです。
よろしくおねがいします。

**Comment by syunin-3** [comment]
v1.0.3で事象を再現させる方法として、Excelで複数のセルを指定して「セルの読み上げ」を行うのが良いようでした。
事象の再現例：SAPIForVOICEVOX v1.0.3 + VOICEVOX v0.5.3 (VOICEVOX:ずんだもん)
https://user-images.githubusercontent.com/47511040/133785279-71e9dfee-ed65-4b52-bab2-cc0516b9fe84.mp4

v1.1.0を導入後は、ノイズが発生しなくなり、Issue#19は解消されているように見えます。
解消後の動作：SAPIForVOICEVOX v1.1.0 + VOICEVOX v0.5.3 (VOICEVOX:ずんだもん)
https://user-images.githubusercontent.com/47511040/133785340-05316e05-05cd-4afd-af20-bb56c89b4732.mp4

また、検証中に別の事象として、v1.0.3では読み上げ出来ていたテキストが途中で中断されるケースを確認しました。
例文：（ソフトのアップデートにはVer0.5.1がないがミスとのこと。）
※「ミスとの」まで発声されて、「こと」が読めない。

何度か再生してみたのですが、毎回同じところで声が聞こえなくなるようでした。
単独で1セルのみ指定して読み上げたときも同様でした。

**Comment by shigobu** [comment]
ありがとうございます。
解決したようなので、issue #19 は閉じます。

途中で中断される問題は、別でissueを立てていただきたいです。
