### ISSUE TITLE
ローマ字が読めるようにしてほしい。

### ISSUE THREAD

**Issue by BURI55** [shigobu/SAPIForVOICEVOX#31]
最近のバージョンで英語が読めるようになったようですが、私としてはローマ字が読めるようにしてほしい。
マイクロソフトのC#用のライブラリInternational Pack 1.0 RC1を利用して、
JpnKanaConversion.dllとJpnKanaConvHelper.dllを利用すればできそう。
ただ、英語読み上げと共存は難しいので、設定でスイッチが必要か？

参考
Faith and Brave - C++で遊ぼう
[C#] KanaConverter
http://d.hatena.ne.jp/faith_and_brave/20080424/1209027626

**Comment by shigobu** [comment]
issueありがとうございます。
こんな便利なライブラリが有ることを知りませんでした。
ぜひとも実装したいです。

英語として読めなかった場合にローマ字読みにする処理でもいいかなと思いました。

もし、実装するとなると、
現在スタイル登録ツールを作っているので、それが完成した後になりそうです。

**Comment by shigobu** [comment]
コメント忘れてました。
バージョン1.2.2で、ローマ字を読む機能を追加しています。
英語として読めなかった場合に、ローマ字読みを行う処理になっています。
