### ISSUE TITLE
拙作のSAPIで選択できるようにしてみました。

### ISSUE THREAD

**Issue by miyabin1701** [shigobu/SAPIForVOICEVOX#55]
VoiceVoxに対応したいと思い、調べているとこちらに行きつきました。
Windows用のプログラムなので、VoiceVoxコアやエンジンのVS201xでのビルドで悩んでいました。
SAPIForVOICEVOXのお陰で簡単に対応できました。有難うございます。
　拙作：https://github.com/miyabin1701/MeCabon　　ライトノベル用テキストファイルリーダです。

　拙作で発声は可能になりましたが、イントネーションがおかしい（拙作でMecabを呼びかな変換しているので）
もし、JTALK内のMecabでイントネーション込みの辞書からのデータにアクセスできないのかもです。
　正式にVoiceVox対応するには、JTALK内のMecabに対応する必要がありそうです。

　VoiceVoxエディターを終了したら、エラー音声が鳴るようなのですが、エンジンやコアのみをロードすることは
出来ないのでしょうか？エディターで発音を変えられるわけではないようですので。
　よろしくお願いします。

**Comment by shigobu** [comment]
エンジンにみの起動でも動作します。
SAPI For VOICEVOXは、起動中のVOICEVOXエンジンへhttpリクエストを送っているだけです。

エンジンは、VOICEVOXのあるフォルダのrun.exeのダブルクリックで起動できます。

**Comment by miyabin1701** [comment]
有難うございます。試してみます。
