### ISSUE TITLE
run.exe起動後、HTTPサービスが動作するまでの間にエクセプションが起こるようです。

### ISSUE THREAD

**Issue by miyabin1701** [shigobu/SAPIForVOICEVOX#57]
こんばんは、　ご教授いただきましたrun.exeを（既にrun.exeかVOICEVOX.exeが起動していないときに）CreatProcessで
起動するようにしました。すると、run.exeは起動しているが、 http://127.0.0.1:50021　のサービスが起動していない時
エクセプションが発生するようになりました。十数秒間エクセプションが続いてrun.exeのコンソールで
Warning: cpu_num_threads is set to 0. ( The library leaves the decision to the synthesis runtime )
INFO:     Started server process [1145988]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:50021 (Press CTRL+C to quit)
２行目以降が表示されたタイミングでエクセプションが起こらなくなりました。
run.exeのコンソールの表示は上記の通りです。
こちらのプログラム中ではエクセプションをキャッチできないようなのですが、通信サービスが
起動しているかどうか判断方法はございますでしょうか？

　ノベルを読ませようとすると、辞書に未定義の語彙が多数出てくるため、未定義語が出てくる度に
ｃｓｖ辞書をテキストエディタで追加して、ある程度溜まったら、１ボタンで辞書ビルドするように
しているため、ＪＴＡＬＫ下のＭｅＣａｂがロックしている辞書ファイルを開放するためにrun.exeを
一旦終了して、辞書のビルド後再起動する必要があるためエクセプションの起こらないhttpサービス
が開始したタイミングが知りたいです。

　run.exeのキャプションで起動しているか確認していると思いますが、VOICEVOX側でキャプションで
httpサービスが始まったら・・・・\run.exe startとか追記出来たらいいのかな？　コンソールアプリで
キャプション設定ってできたのかな？　よろしくお願いします。

**Comment by shigobu** [comment]
エンジンへの接続エラーに関して不具合が有り、プルリクエスト#56 を頂いていました。
ついさっきマージしたので、次のリリースで修正されるはずです。

**Comment by miyabin1701** [comment]
有難うございます。期待しています。

**Comment by shigobu** [comment]
2.0.0をリリースしました。
このアップデートで、エンジンへの接続エラーに関する不具合が修正されています。
run.exeが起動中で、httpサービスの起動前に接続を試みた場合、音声でエラーが通知されます。

**Comment by shigobu** [comment]
httpサービスが起動するまで待機する機能に関しては、実装する予定はありません。
sapiの仕様上、プロセスの起動・終了の制御を自由に行うことができず、VOICEVOXの自動起動を実装していません。また、エンジンプロセス起動中かどうかの判定に「runという名前のプロセスが起動中か」という条件を使用しています。
したがって、httpサービスへのアクセスが失敗した原因が、「httpサービス起動中で待っていれば起動する」のか「同名で関係ないrunプロセスが起動していて、待っていてもVOICEVOXのhttpサービスは起動しない」のか判断できません。後者の場合、フリーズすることになります。タイムアウトを設定するにしても、httpサービス起動時間は個々の環境で異なるため、長い時間を設定する必要があり、その分ユーザーを待たせることになります。

httpサービスが起動しているかの判定方法や起動するまで待機する方法に関しては、VOICEVOX・VOICEVOXエンジンのソースコードを参照してください。VOICEVOXは、起動すると同時にエンジンを起動し、httpサービスが起動するまで待機しています。
