### ISSUE TITLE
SAPI5を使用する場合、プログラムは「、」に続く単語や文章の発音を停止します。さらに、行文字制限により、文が終了する前に文が切り取られます。

### ISSUE THREAD

**Issue by rasbayri** [shigobu/SAPIForVOICEVOX#83]

**Comment by rasbayri** [comment]
例文
知らないことの幸せを得るか、それとも禁忌を犯してでも知ることの喜びを得るか――
もし自分がおじいさん、おばあさんだったとして皆はどうする？
……見る、それとも見ない？
狭き門を突破し、素晴らしい将来が確約されていたのにどうして……
エンジンエラーが発生しないが、読み取りが進まない

**Comment by rasbayri** [comment]
同じです
棒読みちゃんクリップボードを使用しています
VOICEVOXバージョンは0.14.5（GPU)
SAPI３２

**Comment by shigobu** [comment]
問題の切り分けのために、下記の点を確認してください。

使ってるGPUとGPUメモリの容量を教えてください。
CPUモードではどうなりますか？
SAPI For VOICEVOXの設定で「読点(、)で分割する」にチェックを入れるとどうなりますか？

よろしくお願いします。

**Comment by rasbayri** [comment]
AMD RX Vega 10 Graphicsを使用しています。(統合された1GBのGPU、それは32GBRAMを使用しています。はい、それがサポートされていないことを完全に認識していますが、それがこの問題を引き起こしていないにもかかわらず、何とか動作するようにしました)

CPUモードでも全く同じです。使わない理由は、遅すぎるからです。

読点（、）で分割、句点（。）で分割を確認しても、全く変化がなく、問題が解決されません。

**Comment by shigobu** [comment]
VOICEVOX本体では正常に読み上げがされますか？

**Comment by rasbayri** [comment]
はい、全て読み上げられます

**Comment by shigobu** [comment]
うーん、よくわからないですね。
VOICEVOXは以前から、長文での音声合成に不具合が有りました。なので、VOICEVOXエディタでは、句点(。)で分割したり、改行で分割して、一度に行う音声合成の文を短くしていました。

SAPI For VOICEVOXでも、句点(。)や読点(、)で分割するオプションを追加していますが、改行に関しては考慮していませんでした。

このIssueの原因はわかりませんが、一度、「改行で分割する」オプションを追加したバージョンを作成してみるので、それで試してみてください。

**Comment by shigobu** [comment]
改行で分割するオプションを作ってみましたが、それ以前に、棒読みちゃんは改行毎に区切って音声生成を行っているようでした。つまり、棒読みちゃんを使用してると、改行で分割するオプションをonにしてもoffにしてもVOICEVOXに送られる文字データには変わりが無いことになります。

原因不明のままです。私の力では解決できそうにありません。

一応、改行で分割するオプションを追加したものは、
https://github.com/shigobu/SAPIForVOICEVOX/actions/runs/4460626690
の下にあるArtifactsからダウンロードできます。

**Comment by rasbayri** [comment]
お疲れ様でした
