### ISSUE TITLE
イントネーションの変更方法

### ISSUE THREAD

**Issue by htakahashi0901** [shigobu/SAPIForVOICEVOX#84]
windows form c#で音声合成させていただいています。ありがとうございます。
下記のコードを実行したとき「受付番号」のイントネーションを自然にしたいのですがイントネーションを変更することは可能でしょうか。VoiceVoxのエディターを使えば可能であることはわかったのですがコードで可能かどうか教えていただきたいです。宜しくおねがいします。

```
using System;
using System.IO;
using System.Speech.Synthesis;
using System.Windows.Forms;

namespace GenerateSpeech
{
    public partial class Form1 : Form
    {
        private SpeechSynthesizer synthesizer;
        public Form1()
        {
            InitializeComponent();
            synthesizer = new SpeechSynthesizer();
            synthesizer.SelectVoice(synthesizer.GetInstalledVoices()[17].VoiceInfo.Name);
        }

        private void button1_Click(object sender, EventArgs e)
        {
            string inputText = "受付番号87番です。";
            synthesizer.SpeakAsync(inputText);
        }

        private void Form1_Load(object sender, EventArgs e)
        {

        }
    }
}

```
![Untitled](https://user-images.githubusercontent.com/34456571/223973320-39914502-5976-483b-b471-695a54178840.png)

**Comment by shigobu** [comment]
イントネーションとは、VOICEVOXエディタの下に表示されるもののことですよね。
SAPI For VOICEVOX経由でのイントネーションの操作はできません。
操作できるのもは、エディタの右に表示されているものです。これらは、SAPI For VOICEVOXの設定アプリから設定できます。

VOICEVOX本体の「読み方・アクセント辞書」機能を使うと、指定の単語の「読み」と「アクセント」を指定することができます。この辞書は、エンジンに保存されるので、SAPI For VOICEVOXでも反映されるはずです。

C#を使っているのなら、SAPI経由ではなく、直接VOICEVOXエンジンへリクエストを送る方法も使えます。
私のお試しコードが参考になるかもです。
https://github.com/shigobu/VoiceVoxCSConsoleTest
VOICEVOXエンジンの詳細は、本家リポジトリを確認してください。
https://github.com/VOICEVOX/voicevox_engine

よろしくお願いします。

**Comment by htakahashi0901** [comment]
早速のお返事ありがとうございます。辞書と本家リポジトリを試してみます。
